FROM confluentinc/cp-kafka-connect-base:latest

# Install required connectors
#RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest
#RUN confluent-hub install --no-prompt marklogic/kafka-marklogic-connector:1.6.0
#RUN confluent-hub install --no-prompt confluentinc/kafka-connect-rabbitmq-sink:1.5.0
#RUN confluent-hub install --no-prompt confluentinc/kafka-connect-rabbitmq:1.5.0
